
[general]
	"Max Distance" = 24
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 1.0
	"Draw Background" = false
	"Background Padding" = 0
	"Background Height" = 0
	"Health Bar Height" = 5
	"Plate Size" = 30
	"Plate Size (Boss)" = 200
	"Show Attributes" = false
	"Show Armor" = false
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = true
	"HP Text Height" = 15
	"Show Max HP" = false
	"Show Current HP" = true
	"Show HP Percentage" = false
	"Display on Players" = true
	"Display on Bosses" = false
	"Only show the health bar for the entity looked at" = false
	"Show entities with full health" = true
	"Show Debug Info with F3" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish"]
	"Max Distance Without Line of Sight" = 8
	#Text color in hex code format
	text_color = "FFFFFF"
	#Whether bars on passive mobs should be shown
	showOnPassive = true
	#Whether bars on hostile mobs should be shown (does not include bosses)
	showOnHostile = true
	show_entity_name = true
	#Disables the rendering of the vanilla name tag
	disable_name_tag = false

